name:                play
version:             0.1.0.0
license:             Apache-2.0
author:              "Gil Mizrahi"
maintainer:          "gilmi@posteo.net"
copyright:           "2018 Gil Mizrahi"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- async
- containers
- dlist
- transformers
- mtl
- text
- bytestring
- file-embed
- vector
- lens
- bytestring
- linear
- deepseq
- random
- stm
- async
- sdl2
- sdl2-gfx
- sdl2-image
- sdl2-mixer
- sdl2-ttf

library:
  source-dirs: src
  default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - EmptyDataDecls
  - FlexibleContexts
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - PatternGuards
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - NamedFieldPuns
  - ScopedTypeVariables
  - TupleSections
  - ViewPatterns
  - BangPatterns


executables:
  app:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - base
    - optparse-generic
    - play

    ghc-options:
    - -Wall
    - -fno-warn-missing-signatures
    - -Werror
    - -O2
    - -rtsopts
    - -funfolding-use-threshold=16
    - -optc-O3

    default-extensions:
    - ConstraintKinds
    - DataKinds
    - DeriveFunctor
    - EmptyDataDecls
    - FlexibleContexts
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - MultiWayIf
    - PatternGuards
    - PatternSynonyms
    - RankNTypes
    - RecordWildCards
    - NamedFieldPuns
    - ScopedTypeVariables
    - TupleSections
    - ViewPatterns

